Sprint 4
GalenMad/middle.messenger.praktikum.yandex pull request #6
Opened 2022-01-30 19:05 UTC by GalenMad

Привет!

Если ты читаешь это сообщение, значит скорее всего ты мой ревьюер.

У меня возникла сложность с вебпаком: почему-то не распознаются импорты svg-картинок в .scss файлах, поэтому пришлось их скопировать как есть чтобы они отображались. Случайно не знаешь в чём может быть дело?

Также буду рад любой критике.

2022-01-30 21:06 UTC, DmitryKhitrin requested changes
Спасибо за вашу работу, все выглядит супер!) Оставил пару комментариев, посмотрите их пожалуйста. Работу верну,  на случай если вам понадобиться еще проверка. Если не понадобиться присылайте, я все приму)

Удачи!)

2022-01-30 21:44 UTC, GalenMad commented on server.js
> +const PORT = process.env.PORT || 4000;
В прошлый раз не требовали. Я переделаю, там две минуты)

2022-01-30 21:45 UTC, GalenMad commented on src/modules/block/index.ts
> +      // TODO: Разобраться с типами вебпака, тут избыточная проверка
Тут дело в том, что при сборке вебпак выкидывал мне такие ошибки типов, которые раньше не выдавал мне собственный валидатор. Причём независимо от указания конфига.

2022-01-30 21:46 UTC, GalenMad commented on src/modules/controllers/auth.ctrl.ts
> -      this.mutations.setUserInfo(response.data);
Спасибо, я рассмотрю вариант с библиотекой, так как на самом деле много мест в контроллерах, которые я хотел бы пофиксить.

2022-01-30 21:48 UTC, GalenMad commented on webpack.config.js
> +          // TODO: Понять в чём проблема с SVG in CSS (bg url)
Я уже использую `svg-url-loader` и он не помогает, к сожалению. Точнее, он генерирует файлы по папкам, но при этом в корне проекта создаёт дубли этих пустых файлов и на них начинают ссылаться стили. Возможно, что это баг для моего случае, а возможно просто где-то туплю.

2022-01-30 21:49 UTC, GalenMad commented on src/modules/block/index.ts
> +      // TODO: Разобраться с типами вебпака, тут избыточная проверка
Но я уже думаю, что это ок, нужно просто немного детальнее проработать типы и проверки.

2022-01-30 22:00 UTC, GalenMad commented on src/modules/controllers/auth.ctrl.ts
> -      this.mutations.setUserInfo(response.data);
Действительно, typescript-is выглядит интересно, попробую его, а пока не буду костылять.

2022-02-02 20:39 UTC, DmitryKhitrin approved these changes

2022-02-17 22:41 UTC, merged